version: '3.9'

services:
  book.izdrail.com:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER:-1000}'
        WWWGROUP: '${WWWGROUP:-1001}'
    image: izdrail/book.izdrail.com
    container_name: book.izdrail.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '1602:1602'
      - '1603:1603'
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'
    volumes:
      - '.:/app'
    networks:
      - sail

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /home/sb1/.ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    # Uncomment if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - sail

networks:
  sail:
    driver: bridge
